version: '3.9'

services:
  db:
    image: postgres:16
    container_name: ifreela-db
    environment:
      POSTGRES_USER: ifreela
      POSTGRES_PASSWORD: ifreela123
      POSTGRES_DB: ifreela
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
